services:
  aws-wrapper:
    image: aws-wrapper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - db_url=${DB_URL}
      - db_username=${DB_USERNAME}
      - db_password=${DB_PASSWORD}
